# Generated by Django 4.1.3 on 2024-06-19 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rarev2api', '0002_posts'),
    ]

    operations = [
        migrations.CreateModel(
            name='RareUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('bio', models.CharField(max_length=50)),
                ('profile_image_url', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('created_on', models.DateField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('uid', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='posts',
            name='rare_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rarev2api.rareusers'),
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
