# Generated by Django 4.1.3 on 2024-06-20 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rarev2api', '0004_rename_rareusers_rareuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
    ]
